language: php
sudo: false

php:
  - 7.0
  - 7.1
  - 7.2

before_script:
  - composer install -n

script:
  - ./vendor/bin/phpcs --standard=psr2 . --ignore='/vendor|_cache/'
  - ./vendor/bin/phpstan analyse -l max -c phpstan.neon src/ public/ *.php
